const SETFILENAME = 'setFileName'; // 同步
const ASYNC_SETFILENAME = 'asyncSetFileName'; //异步
const SETMENUVISIBLE = 'setMenuVisible';
const ASYNC_SETMENUVISIBLE = 'asyncSetMenuVisible';
const SET_SETTINGVISIBLE = 'settingVisible';
const ASYNC_SET_SETTINGVISIBLE = 'asyncSettingVisible';
const SET_DEFAULTFONTSIZE = 'setDefaultFontSize';
const ASYNC_SET_DEFAULTFONTSIZE = 'asyncSetDefaultFontSize';
export {
  SETFILENAME,
  ASYNC_SETFILENAME,
  SETMENUVISIBLE,
  ASYNC_SETMENUVISIBLE,
  SET_SETTINGVISIBLE,
  ASYNC_SET_SETTINGVISIBLE,
  SET_DEFAULTFONTSIZE,
  ASYNC_SET_DEFAULTFONTSIZE
};
